### ISSUE TITLE
window pip install error

### ISSUE THREAD

**Issue by uiolee** [zombie110year/caj2pdf-restructured#3]
pip install caj2pdf-restructured

```
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for caj2pdf-restructured
Failed to build caj2pdf-restructured
ERROR: Could not build wheels for caj2pdf-restructured, which is required to install pyproject.toml-based projects
```

### error

<details><summary>
错误信息:</summary>
<p>

```shell
$ pip install caj2pdf-restructured

Defaulting to user installation because normal site-packages is not writeable
Collecting caj2pdf-restructured
  Using cached caj2pdf-restructured-0.1.0a7.tar.gz (53 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting PyPDF2==2.2.0 (from caj2pdf-restructured)
  Using cached PyPDF2-2.2.0-py3-none-any.whl (189 kB)
Collecting imagesize==1.3.0 (from caj2pdf-restructured)
  Using cached imagesize-1.3.0-py2.py3-none-any.whl (5.2 kB)
Building wheels for collected packages: caj2pdf-restructured
  Building wheel for caj2pdf-restructured (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for caj2pdf-restructured (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [52 lines of output]
      Traceback (most recent call last):
        File "C:\Users\username\AppData\Local\Temp\pip-install-vide39n9\caj2pdf-restructured_6fc850e995be483eaa5273e09beb12a7\setup.py", line 49, in <module>
          build(setup_kwargs)
        File "C:\Users\username\AppData\Local\Temp\pip-install-vide39n9\caj2pdf-restructured_6fc850e995be483eaa5273e09beb12a7\build.py", line 80, in build
          t.hardlink_to(s)
        File "C:\Program Files\Python311\Lib\pathlib.py", line 1208, in hardlink_to
          os.link(target, self)
      FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'dlls\\libjbigdec-w32.dll' -> 'build\\caj2pdf\\dep\\bin\\libjbigdec-w32.dll'
       - Adding caj2pdf/__init__.py
       - Adding caj2pdf/cajparser.py
       - Adding caj2pdf/cli.py
       - Adding caj2pdf/dep/__init__.py
       - Adding caj2pdf/dep/decode_jbig2data.cc
       - Adding caj2pdf/dep/decode_jbig2data_x.cc
       - Adding caj2pdf/dep/jbig2dec.py
       - Adding caj2pdf/dep/jbigdec.cc
       - Adding caj2pdf/dep/jbigdec.py
       - Adding caj2pdf/dep/JBigDecode.cc
       - Adding caj2pdf/dep/JBigDecode.h
       - Adding caj2pdf/exceptions.py
       - Adding caj2pdf/exe_convert.py
       - Adding caj2pdf/HNParsePage.py
       - Adding caj2pdf/install.py
       - Adding caj2pdf/pdfwutils.py
       - Adding caj2pdf/utils.py
       - Adding caj2pdf/version.py
      Traceback (most recent call last):
        File "C:\Users\username\AppData\Local\Temp\pip-build-env-kkrrxf2e\overlay\Lib\site-packages\pdm\pep517\wheel.py", line 274, in _build
          subprocess.check_call(build_args)
        File "C:\Program Files\Python311\Lib\subprocess.py", line 413, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['C:\\Program Files\\Python311\\python.exe', 'C:\\Users\\username\\AppData\\Local\\Temp\\pip-install-vide39n9\\caj2pdf-restructured_6fc850e995be483eaa5273e09beb12a7\\setup.py', 'build', '-b', 'C:\\Users\\username\\AppData\\Local\\Temp\\pip-install-vide39n9\\caj2pdf-restructured_6fc850e995be483eaa5273e09beb12a7\\build']' returned non-zero exit status 1.

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "C:\Users\username\AppData\Roaming\Python\Python311\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\username\AppData\Roaming\Python\Python311\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\username\AppData\Roaming\Python\Python311\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\username\AppData\Local\Temp\pip-build-env-kkrrxf2e\overlay\Lib\site-packages\pdm\pep517\api.py", line 75, in build_wheel
          builder.build(wheel_directory, metadata_directory=metadata_directory)
        File "C:\Users\username\AppData\Local\Temp\pip-build-env-kkrrxf2e\overlay\Lib\site-packages\pdm\pep517\wheel.py", line 160, in build
          self._build()
        File "C:\Users\username\AppData\Local\Temp\pip-build-env-kkrrxf2e\overlay\Lib\site-packages\pdm\pep517\wheel.py", line 276, in _build
          raise BuildError(f"Error occurs when running {build_args}:\n{e}")
      pdm.pep517.exceptions.BuildError: Error occurs when running ['C:\\Program Files\\Python311\\python.exe', 'C:\\Users\\username\\AppData\\Local\\Temp\\pip-install-vide39n9\\caj2pdf-restructured_6fc850e995be483eaa5273e09beb12a7\\setup.py', 'build', '-b', 'C:\\Users\\username\\AppData\\Local\\Temp\\pip-install-vide39n9\\caj2pdf-restructured_6fc850e995be483eaa5273e09beb12a7\\build']:
      Command '['C:\\Program Files\\Python311\\python.exe', 'C:\\Users\\username\\AppData\\Local\\Temp\\pip-install-vide39n9\\caj2pdf-restructured_6fc850e995be483eaa5273e09beb12a7\\setup.py', 'build', '-b', 'C:\\Users\\username\\AppData\\Local\\Temp\\pip-install-vide39n9\\caj2pdf-restructured_6fc850e995be483eaa5273e09beb12a7\\build']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for caj2pdf-restructured
Failed to build caj2pdf-restructured
ERROR: Could not build wheels for caj2pdf-restructured, which is required to install pyproject.toml-based projects
```

</p>
</details> 

### version
windows 10
Python 3.11.4
pip 23.2.1

**Comment by chen-huaneng** [comment]
I encountered the same error message in Windows 10
## Version
pip 23.3.1
python 3.11.2
## pip list
Package    Version
---------- -------
pip        23.3.1
setuptools 68.2.2
wheel      0.41.2
